#!/bin/bash
code --install-extension aaron-bond.better-comments \
code --install-extension alefragnani.project-manager \
code --install-extension apollographql.vscode-apollo \
code --install-extension arturock.gitstash \
code --install-extension christian-kohler.npm-intellisense \
code --install-extension christian-kohler.path-intellisense \
code --install-extension chrmarti.regex \
code --install-extension codezombiech.gitignore \
code --install-extension CoenraadS.bracket-pair-colorizer \
code --install-extension cssho.vscode-svgviewer \
code --install-extension dbaeumer.vscode-eslint \
code --install-extension docsmsft.docs-article-templates \
code --install-extension donjayamanne.githistory \
code --install-extension DotJoshJohnson.xml \
code --install-extension eamodio.gitlens \
code --install-extension eg2.vscode-npm-script \
code --install-extension esbenp.prettier-vscode \
code --install-extension formulahendry.auto-close-tag \
code --install-extension formulahendry.auto-rename-tag \
code --install-extension formulahendry.code-runner \
code --install-extension ghmcadams.lintlens \
code --install-extension hoovercj.vscode-power-mode \
code --install-extension IBM.output-colorizer \
code --install-extension jock.svg \
code --install-extension joelday.docthis \
code --install-extension joshpeng.theme-onedark-sublime \
code --install-extension Kasik96.swift \
code --install-extension kumar-harsh.graphql-for-vscode \
code --install-extension lamartire.git-indicators \
code --install-extension mechatroner.rainbow-csv \
code --install-extension mgmcdermott.vscode-language-babel \
code --install-extension mikestead.dotenv \
code --install-extension mrmlnc.vscode-json5 \
code --install-extension ms-python.python \
code --install-extension ms-vscode.typescript-javascript-grammar \
code --install-extension ms-vsliveshare.vsliveshare \
code --install-extension naumovs.color-highlight \
code --install-extension OfHumanBondage.react-proptypes-intellisense \
code --install-extension Orta.vscode-jest \
code --install-extension pflannery.vscode-versionlens \
code --install-extension redhat.vscode-yaml \
code --install-extension shd101wyy.markdown-preview-enhanced \
code --install-extension shinnn.stylelint \
code --install-extension sourcegraph.javascript-typescript \
code --install-extension uyiosa-enabulele.reopenclosedtab \
code --install-extension VisualStudioExptTeam.vscodeintellicode \
code --install-extension vscode-icons-team.vscode-icons \
code --install-extension vsmobile.vscode-react-native \
code --install-extension WakaTime.vscode-wakatime \
code --install-extension wayou.vscode-todo-highlight \
code --install-extension xabikos.JavaScriptSnippets \
code --install-extension zhouronghui.propertylist \
code --install-extension zhuangtongfa.Material-theme \